- name: Install nginx and register rhel
  hosts: "{{ ec2_scope }}"
  become: true
  user: ec2-user

  roles:
    - role: nginxinc.nginx

  tasks:

    - name: Install RHSM and Insights
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - redhat-access-insights
        - subscription-manager
      
    - name: Register system
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"




