---

- name: Get facts for a set of instances
  gce:
    base_name: "{{ scope }}"
    num_instances: "{{ gce_count }}"
    zone: "{{ gce_zone }}"
    project_id: "{{ gce_project_id }}"
    state: present
  register: gce_instances

- name: Build a list of ips and hostnames
  vars:
    ips_to_add: "{{ gce.instances | map(attribute='public_ip') | list }}"
  set_fact:
    ips_to_add: "{{ ips_to_add }}"

- debug:
    var: ips_to_add
