---

- include_role: 
    name: common
    tasks_from: gce_env

- name: create a network
  gcp_compute_network:
    name: "{{ gce_scope }}-network"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network

- name: Create Firewall Rule for SSH
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-ssh"
    allowed: tcp:22
    state: present
    src_range: ['0.0.0.0/0']

- name: Create Firewall Rule for HTTP
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-http"
    allowed: tcp:80
    state: present
    src_range: ['0.0.0.0/0']

# - name: create a instance group
#   gcp_compute_instance_group:
#     name: "{{ gce_scope }}-ig"
#     named_ports:
#       - name: http
#         port: 80
#     network: "{{ network }}"
#     zone: "{{ gce_zone }}"
#     project: "{{ gce_project_id }}"
#     auth_kind: serviceaccount
#     service_account_file: "{{ gcp_cred_file.path }}"
#     scopes:
#       - https://www.googleapis.com/auth/compute
#     state: present
#   register: ig

- name: create instances loop
  include_role: 
    name: gce
    tasks_from: gce_create_elements
  with_sequence: count="{{gce_count}}" 








