---

- name: Get facts for a set of instances
  gce:
    base_name: "{{ scope }}"
    num_instances: "{{ gce_count }}"
    zone: "{{ gce_zone }}"
    project_id: "{{ gce_project_id }}"
    state: present
  register: gce

- debug:
    var: gce.instance_data   

- name: Build a list of ips and hostnames
  vars:
    ips_to_add: "{{ gce.instance_data  | map(attribute='public_ip') | list }}"
  set_fact:
    ips_to_add: "{{ ips_to_add }}" 
  
- name: Add hosts
  add_host:
    name: "{{ item }}"
    groups: "{{ gce_scope }}"
  with_items: "{{ ips_to_add }}" 

- name: Wait for SSH to come up
  wait_for_connection:
    timeout: 600
    sleep: 15
  delegate_to: "{{ item }}"
  with_items: "{{ ips_to_add }}"

