---

- include_role: 
    name: common
    tasks_from: gce_env

- name: Remove IG from backend service
  shell: |
    gcloud auth activate-service-account --key-file "{{ gcp_cred_file.path }}"
    gcloud compute backend-services remove-backend "{{ gce_lb }}" \
      --instance-group="{{ gce_scope }}-ig" \ 
      --global  \ 
      --instance-group-zone "{{ gce_zone }}"
  delegate_to: localhost

- name: Remove instances group from IG
  shell: |
    gcloud compute instance-groups unmanaged remove-instances "{{ gce_scope }}-ig" \
      --instances="{{ gce_scope }}" \
      --project "{{ gce_project_id }}" \  
      --zone "{{ gce_zone }}"
  delegate_to: localhost

- name: Remove instance group
  shell: |
    gcloud compute instance-groups unmanaged delete "{{ gce_scope }}-ig" \
      --project "{{ gce_project_id }}" \  
      --zone "{{ gce_zone }}"
  delegate_to: localhost

- name: Remove instances
  gce:
    base_name: "{{ scope }}"
    zone: "{{ gce_zone }}"
    project_id: "{{ gce_project_id }}"
    state: absent

- name: remove addresse
  gcp_compute_address:
    name: "{{ gce_scope }}-address"
    region: "{{ gce_region }}"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: absent
 
- name: Delete Firewall Rule for SSH
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-ssh"
    state: absent

- name: Delete Firewall Rule for SSH
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-ssh"
    state: absent

- name: Delete Firewall Rule for HTTP
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-http"
    state: absent

- name: remove a network
  gcp_compute_network:
    name: "{{ gce_scope }}-network"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: absent

- name: remove disk
  gcp_compute_disk:
      name: "{{ gce_scope }}-disk"
      zone: "{{ gce_zone }}"
      project: "{{ gce_project_id }}"
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file.path }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent

# - debug:
#     var: gcp_ips

# - name: create public ips
#   gce_eip:
#     project_id: "{{ gce_project_id }}"
#     name: "{{ gce_scope }}-publicip-{{ item }}"
#     region: "{{ gce_region }}"
#     state: present
#   register: gcp_public_ips
#   with_sequence: count="{{gce_count}}" 



