---

- name: Get facts for a set of instances
  gce:
    base_name: "{{ scope }}"
    num_instances: "{{ gce_count }}"
    zone: "{{ gce_zone }}"
    project_id: "{{ gce_project_id }}"
    state: present
  register: gce_instances

- debug:
    var: gce_instances


