---
- include_role: 
    name: common
    tasks_from: gce_env
    
- name: Add IG to backend service
  shell: |
    gcloud auth activate-service-account --key-file "{{ gcp_cred_file.path }}"
    gcloud compute backend-services add-backend "{{ gce_lb }}" \
      --instance-group="{{ gce_scope }}-ig" \ 
      --global  \ 
      --project "{{ gce_project_id }}" \  
      --instance-group-zone "{{ gce_zone }}"
  delegate_to: localhost
  ignore_errors: yes