---
# - name: Provision a set of instances
#   gce:
#     base_name: "{{ scope }}"
#     num_instances: "{{ gce_count }}"
#     zone: "{{ gce_zone }}"
#     machine_type: "{{ gce_machine_type }}"
#     image: https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/images/rhel-7-v20180716
#     project_id: "{{ gce_project_id }}"
#     state: started
#     disk_size: 64

- name: create temporary file for the gce json 
  tempfile:
    state: file
    suffix: gce
  register: gcp_cred_file
  delegate_to: localhost
  run_once: yes
  become: no

# - copy:
#     content: "{{ lookup('template', './files/gce.json.j2', convert_data=False) }}" 
#     dest: "{{ gcp_cred_file.path }}"

- template: 
    src: "./files/gce.json.j2"
    dest: "{{ gcp_cred_file.path }}"

- debug:
    var: "{{ lookup('file', gcp_cred_file.path) }}"

- name: create a disk
  gcp_compute_disk:
      name: 'disk-instance'
      size_gb: 50
      source_image: 'rhel-7'
      zone: "{{ gce_zone }}"
      project: "{{ gce_project_id }}"
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file.path }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: disk

- name: create a network
  gcp_compute_network:
      name: 'network-instance'
      project: "{{ gce_project_id }}"
      # auth_kind: "{{ gcp_cred_kind }}"
      # service_account_file: "{{ gcp_cred_file }}"
      # scopes:
      #   - https://www.googleapis.com/auth/compute
      state: present
  register: network

- name: create a address
  gcp_compute_address:
      name: 'address-instance'
      zone: "{{ gce_zone }}"
      project: "{{ gce_project_id }}"
      # auth_kind: "{{ gcp_cred_kind }}"
      # service_account_file: "{{ gcp_cred_file }}"
      # scopes:
      #   - https://www.googleapis.com/auth/compute
      state: present
  register: address

- name: create a instance
  gcp_compute_instance:
      name: testObject
      machine_type: n1-standard-1
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
      # metadata:
      #   startup-script-url: 'gs:://graphite-playground/bootstrap.sh'
      #   cost-center: '12345'
      network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
           
      zone: "{{ gce_zone }}"
      project: "{{ gce_project_id }}"
      # auth_kind: service_account
      # service_account_file: /tmp/auth.pem
      # scopes:
      #   - https://www.googleapis.com/auth/compute
      state: present