---
- name: Provision a set of instances
  gce:
    base_name: "{{ scope }}"
    num_instances: "{{ gce_count }}"
    zone: "{{ gce_zone }}"
    machine_type: "{{ gce_machine_type }}"
    image: "{{ gce_image }}"
    project_id: "{{ gce_project_id }}"
    state: started
    disk_size: 64
  register: gce

- debug:
    var: gce.instance_data 