---
- name: Provision a set of instances
  gce:
    base_name: "{{ scope }}"
    num_instances: "{{ gce_count }}"
    zone: "{{ gce_zone }}"
    machine_type: "{{ gce_machine_type }}"
    image: rhel-7-v20180716
    project_id: "{{ gce_project_id }}"
    state: started
    disk_size: 64