---

- include_role: 
    name: common
    tasks_from: gce_env

- environement:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_cred_file.path }}"

- name: create a network
  gcp_compute_network:
    name: "{{ gce_scope }}-network"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network

- name: Create Firewall Rule for SSH
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-ssh"
    allowed: tcp:22
    state: present
    src_range: ['0.0.0.0/0']

- name: Create Firewall Rule for HTTP
  gce_net:
    name: "{{ gce_scope }}-network"
    fwname: "{{ gce_scope }}-http"
    allowed: tcp:80
    state: present
    src_range: ['0.0.0.0/0']

- name: create a instance group
  gcp_compute_instance_group:
    name: "{{ gce_scope }}-ig"
    named_ports:
      - name: http
        port: 80
    network: "{{ network }}"
    zone: "{{ gce_zone }}"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: ig

- debug:
    var: ig 

- name: create disk
  gcp_compute_disk:
      name: "{{ gce_scope }}-disk"
      size_gb: 50
      source_image: 'https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/images/rhel-7-v20180716'
      zone: "{{ gce_zone }}"
      project: "{{ gce_project_id }}"
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file.path }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: gcp_disk

- name: reserve addresse
  gcp_compute_address:
    name: "{{ gce_scope }}-address"
    region: "{{ gce_region }}"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: gcp_ip

- name: create instances
  gcp_compute_instance:
    name: "{{ gce_scope }}"
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ gcp_disk }}"
    metadata:
      unit: "{{ gce_scope }}"
    network_interfaces:
        - network: "{{ network }}"
          access_configs:
            - name: 'External NAT'
              nat_ip: "{{  gcp_ip }}"
              type: 'ONE_TO_ONE_NAT'
    zone: "{{ gce_zone }}"
    project: "{{ gce_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file.path }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present

- name: Add instances to IG
  uri:
    url: "https://www.googleapis.com/compute/v1/projects/{{ gce_project_id }}/zones/{{ gce_zone }}/instanceGroups/{{ gce_scope }}-ig/addInstances"
    method: POST
    body: "{{ lookup('template', './files/ig.json.j2') }}" 








