---

- name: Get facts for network interfaces
  azure_rm_networkinterface_facts:
    resource_group: "{{ az_resourcegroup_name }}"
    name: "nic-{{ az_scope }}-{{ item }}"
  with_sequence: count="{{az_count}}" 
  register: nics

- name: Initialize an empty list 
  set_fact:
    networkinterfaces: []
    ips_to_add: []

- name: Extract azure_networkinterfaces
  vars:
    iterator:  "{{ item.ansible_facts.azure_networkinterfaces }}"
  set_fact:
    networkinterfaces:  "{{ networkinterfaces + iterator  }}"
  loop:  "{{ nics.results }}"

- name:  Extract privateIPAddress
  vars:
    iterator:  "{{ item.properties.ipConfigurations.0.properties.privateIPAddress }}"
    iterator_list: [ '{{ iterator }}' ]
  set_fact:
    ips_to_add: "{{ ips_to_add +  iterator_list }}"
  loop:  "{{ networkinterfaces }}"

- debug:
    msg: "{{ ips_to_add }}"

  # set_fact:
  #   ips_to_add: "{{ ips_to_add }}"

# - name: Build a list of ips and hostnames
#   debug:
#     var: item
#   loop:  "{{ nics.results }}"

# - debug:
#     var: ips_to_add

- name: Add hosts
  add_host:
    name: "{{ item }}"
    groups: "{{ az_scope }}"
  with_items: "{{ ips_to_add }}" 

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 15
    timeout: 600
    state: started
  with_items: "{{ ips_to_add }}"