---

- name: Get facts for network interfaces
  azure_rm_networkinterface_facts:
    resource_group: "{{ az_resourcegroup_name }}"
    name: "nic-{{ az_scope }}-{{ item }}"
  with_sequence: count="{{az_count}}" 
  register: nics

# - debug:
#     var: nics


- name: Initialize an empty list for our strings
  set_fact:
    i: []

- name: Build a list of ips and hostnames
  vars:
    k:  "{{ item.ansible_facts.azure_networkinterfaces }}"
  set_fact:
    i:  "{{ i + k  }}"
  loop:  "{{ nics.results }}"

- name: Build a list of ips and hostnames 2
  vars:
    k:  "{{ item.properties.ipConfigurations.0.properties.privateIPAddress }}"
  set_fact:
    j: "{{ j + k }}"
  loop:  "{{ i }}"

- debug:
    msg: "{{ j }}"

  # set_fact:
  #   ips_to_add: "{{ ips_to_add }}"

# - name: Build a list of ips and hostnames
#   debug:
#     var: item
#   loop:  "{{ nics.results }}"

# - debug:
#     var: ips_to_add

- name: Add hosts
  add_host:
    name: "{{ item }}"
    groups: "{{ az_scope }}"
  with_items: "{{ ips_to_add }}" 

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 15
    timeout: 600
    state: started
  with_items: "{{ ips_to_add }}"