---

- name: provision a set of instances
  azure_rm_virtualmachine:
    resource_group: "{{ az_groupid }}"
    name: "{{ az_scope }}"
    availability_set: "{{ az_set }}"
    vm_size: Standard_B1s   
    managed_disk_type: Standard_LRS
    ssh_password_enabled: False 
    admin_username: "{{ ssh_username }}"
    ssh_public_keys:
      - path: "/home/{{ ssh_username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key }}"
    image:
      offer: RHEL
      publisher: RedHat
      sku: '7-LVM'
      version: latest
    data_disks:
      - lun: 0
        disk_size_gb: 30
        managed_disk_type: Standard_LRS
  with_sequence: count=2 
  register: azure

- debug:
    var: azure


