---

- name: Create network interfaces with private IP
  azure_rm_networkinterface:
        name: "nic-{{ az_scope }}-{{ item }}"
        resource_group: "{{ az_groupid }}"
        virtual_network_name: "{{ az_vnet }}"
        subnet_name: "{{ az_subnet }}"
        public_ip: no
  with_sequence: count="{{az_count}}" 


- name: provision a set of instances
  azure_rm_virtualmachine:
    resource_group: "{{ az_groupid }}"
    name: "{{ az_scope }}-{{ item }}"
    availability_set: "{{ az_set }}"
    network_interfaces: "nic-{{ az_scope }}-{{ item }}"
    subnet_name: default
    vm_size: Standard_B1s   
    managed_disk_type: Standard_LRS
    ssh_password_enabled: False 
    admin_username: "{{ ssh_username }}"
    ssh_public_keys:
      - path: "/home/{{ ssh_username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key }}"
    image:
      offer: RHEL
      publisher: RedHat
      sku: '7-LVM'
      version: latest
    data_disks:
      - lun: 0
        disk_size_gb: 30
        managed_disk_type: Standard_LRS
  async: 1000
  poll: 0 
  with_sequence: count="{{az_count}}" 




