---

- name: remove a set of instances
  azure_rm_virtualmachine:
    resource_group: "{{ az_groupid }}"
    name: "{{ az_scope }}-{{ item }}"
    state: absent
    remove_on_absent: all
  async: 1000
  poll: 0 
  with_sequence: count="{{az_count}}" 



