---

- name: Create network interfaces with private IP
  azure_rm_networkinterface:
        name: "nic-{{ az_scope }}-{{ item }}"
        resource_group: "{{ az_groupid }}"
        virtual_network_name: "{{ az_vnet }}"
        subnet_name: "{{ az_subnet }}"
        state: absent
  with_sequence: count="{{az_count}}" 

- name: remove a set of instances
  azure_rm_virtualmachine:
    resource_group: "{{ az_groupid }}"
    name: "{{ az_scope }}-{{ item }}"
    state: absent
    remove_on_absent: all
  async: 1000
  poll: 0 
  with_sequence: count="{{az_count}}" 



