---

- name: remove a set of instances
  azure_rm_virtualmachine:
    resource_group: "{{ az_groupid }}"
    name: "{{ az_scope }}-{{ item }}"
    state: absent
    remove_on_absent: all
  async: 5000
  poll: 15
  with_sequence: count="{{az_count}}" 
  ignore_errors: yes

- name: remove associated network interfaces 
  azure_rm_networkinterface:
    name: "nic-{{ az_scope }}-{{ item }}"
    resource_group: "{{ az_groupid }}"
    state: absent
  with_sequence: count="{{az_count}}" 
  ignore_errors: yes

- name: remove associated disks 
  azure_rm_managed_disk:
    name: "{{ az_scope }}-{{ item }}"
    resource_group: "{{ az_groupid }}"
    state: absent
  with_sequence: count="{{az_count}}" 
  ignore_errors: yes

