---

- name: App actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes
  
  vars:
    state: "{{ state }}"
  
  tasks:

    # - name: Install needed software
    #   include_role:
    #     name: app
    #     tasks_from: config_nginx

    - name: Install the app
      include_role: 
        name: app
        tasks_from: install_app


- name: ec2 LB actions
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: ec2 add to lb
      include_role: 
        name: ec2
        tasks_from: ec2_elb_target

