---

- name: App actions
  hosts: amazon
  gather_facts: no

  tasks:

    - name: Install needed software
      include_role:
        name: app
        tasks_from: config_nginx

    - name: Install the app
      vars:
        state: "{{ state }}"
      include_role: 
        name: app
        tasks_from: install_app
    

- name: ec2 LB actions
  hosts: localhost
  gather_facts: no

  tasks:

    - name: ec2 add to lb
      include_role: 
        name: ec2
        tasks_from: ec2_elb_target
      tags: elb      


