---

- name: App actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes

  vars:
    state: "{{ state }}"
    app_action: "{{ app_action }}"
  
  tasks:

    - name: Check app already installed     
      stat: 
        path: /app/app/
      register: app_dir

    - name: Remove existing app
      include_role: 
        name: app
        tasks_from: remove_app
      when:
        - app_action == "update"
        - app_dir.stat.exists 

    - name: Configure system
      include_role: 
        name: app
        tasks_from: config_system
      when:
        - app_action != "update"
        - not app_dir.stat.exists

    - name: Install the app
      include_role: 
        name: app
        tasks_from: install_app
      when:
        - not app_dir.stat.exists


- name: ec2 LB actions
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    state: "{{ state }}"
    app_action: "{{ app_action }}"

  tasks:

    - name: ec2 add to lb
      include_role: 
        name: ec2
        tasks_from: ec2_elb_target
      when:
        app_action != "update"

