---

- name: App actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes

  tasks:

    - name: Install needed software
      include_role:
        name: app
        tasks_from: config_nginx
      tags: deploy

  handlers:

    - name: restart_nginx
      service:
        name: nginx
        state: restarted


- name: ec2 LB actions
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Install the app
      vars:
        state: "{{ state }}"
      include_role: 
        name: app
        tasks_from: install_app
      tags: deploy

    - name: ec2 add to lb
      include_role: 
        name: ec2
        tasks_from: ec2_elb_target
      tags: 
        - deploy


