---

- name: App actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes
  serial: 1
  
  vars:
    state: "{{ state }}"
    app_action: "{{ app_action }}"
  
  tasks:

    - name: Remove existing app
      include_role: 
        name: app
        tasks_from: remove_app
      when:
        app_action == "update"

    - name: Configure system
      include_role: 
        name: app
        tasks_from: config_system
      when:
        app_action != "update"

    - name: Install the app
      include_role: 
        name: app
        tasks_from: install_app




