---

- name: App actions
  hosts: amazon
  gather_facts: no

  tasks:

    - name: Install software
      include_role:
        name: app
        tasks_from: config_nginx

    - name: Git get the app
      vars:
        state: "{{ state }}"
      include_role: 
        name: app
        tasks_from: install_app
    


# - name: rhel actions
#   hosts: "*{{ ec2_scope }}"
#   user: ec2-user
#   gather_facts: no

#   tasks:

#   - name: rhel register
#     include_role: 
#       name: common
#       tasks_from: rhel_register
#     tags: create


- name: ec2 LB actions
  hosts: localhost
  gather_facts: no

  tasks:

    - name: ec2 add to lb
      include_role: 
        name: ec2
        tasks_from: ec2_elb_target
      tags: elb      


