---

- name: App actions
  hosts: "*{{ scope }}"
  gather_facts: yes
  become: yes

  tasks:

    - name: Configure system
      include_role: 
        name: app
        tasks_from: config_system
    
    - name: Install the app
      include_role: 
        name: app
        tasks_from: install_app
    