---

- name: App actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes
  serial: 1
  
  vars:
    state: "{{ state }}"
  
  tasks:

    - name: Remove existing app
      include_role: 
        name: app
        tasks_from: remove_app

    - name: Install needed software
      include_role:
        name: app
        tasks_from: config_system

    - name: Install the app
      include_role: 
        name: app
        tasks_from: install_app




