---
- name: azure actions
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "azure create"
    include_role: 
      name: azure
      tasks_from: az_create

- name: azure add host
  hosts: localhost
  tasks:
  - include_role: 
      name: azure
      tasks_from: az_add_host

- name: Deploy app
  import_playbook: app.yml

