- name: Create selfsigned certs
  hosts: all
  become: true

  tasks:
    
  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /home/certs/nginx.key.pem
    delegate_to: localhost

  - name: Generate an OpenSSL CSR
    openssl_csr:
      path: /home/certs/nginx.csr
      privatekey_path: /home/certs/nginx.key.pem
      common_name: "{{ ansible_nodename }}"
      subject_alt_name: '"{{ ansible_hostname }}"'
    delegate_to: localhost
  
  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /home/certs/nginx.crt
      privatekey_path: /home/certs/nginx.key.pem
      csr_path: /home/certs/nginx.csr
      provider: selfsigned
    delegate_to: localhost





