- name: Create selfsigned certs
  hosts: all
  become: True
  user: ec2-user

  tasks:

  - name: Creates cert directory
    file: 
      path: /etc/nginx/ssl
      state: directory
      owner: root
      group: root
      mode: 0600
    
  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /etc/nginx/ssl/{{ ansible_nodename }}.pem

  - name: Generate an OpenSSL CSR
    openssl_csr:
      path: /etc/nginx/ssl/{{ ansible_nodename }}.csr
      privatekey_path: /etc/nginx/ssl/{{ ansible_nodename }}.pem
      common_name: "{{ ansible_nodename }}"
      subject_alt_name: '"{{ ansible_hostname }}"'
  
  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /etc/nginx/ssl/{{ ansible_nodename }}.crt
      privatekey_path: /etc/nginx/ssl/{{ ansible_nodename }}.pem
      csr_path: /etc/nginx/ssl/{{ ansible_nodename }}.csr
      provider: selfsigned





