- name: Install/Remove NginX and Register/Unregister rhel
  hosts: amazon
  user: ec2-user
  become: yes

  tasks:

    - debug:
        msg: state

    - name: Register
      include_tasks: rhel_register.yml
      when: state == "present"

    - name: Install
      include_role:
        name: nginxinc.nginx
      when: state == "present"

    - name: Remove
      include_tasks: remove_nginx.yml
      when: state == "absent"