- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         region: eu-west-1 
         instance_type: t2.micro
         image: ami-ecc27c95
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         assign_public_ip: no
         key_name: my_key
         group: test
      register: ec2