---
- name: Change security group of an instance
  hosts: localhost
  connection: local
  gather_facts: no
  user: ec2-user

  tasks: 

    - name: Change security group of an instance
      ec2:
        region: "{{ ec2_region }}" 
        vpc_subnet_id: "{{ ec2_subnetid }}"
        group_id: "{{ ec2_groupid }}"
        state: running
        instance_ids:
          - i-061b1e2a76f671456
