- name: create ec2 instances  
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: dcl
         state: present
         region: eu-west-1 
         instance_type: t2.micro
         image: ami-ecc27c95
         wait: true
         count: "{{ aws_ec2_count }}"
         instance_tags:
            Name: "{{ aws_ec2_name }}"
         group_id: "{{ aws_ec2_groupid }}"

      register: ec2

    # - name: Output the ec2 return values
    #   debug:
    #     msg: "{{ ec2 }}"

    - name: Initialize an list of instances id and ports
      set_fact:
        ids_and_ports: []

    - name: Build the list of instances id and ports
      set_fact:
        iter: 'toto'
        ids_and_ports: "{{ ids_and_ports }} + {{ iter }}" 
      with_items: "{{ ec2.instance_ids }}"


    - name: Output the ids_and_ports fact
      debug:
        msg: "{{ ids_and_ports }}"

    # - name: Add Instances to LB target 
    #   elb_target_group:
    #     name: "{{ aws_lb_target }}"
    #     protocol: https
    #     port: 80
    #     vpc_id: vpc-01234567
    #     modify_targets: True
    #     state: present
    #     target_type: instance
    #     instances: "{{ ids_ports}}"

