- name: create gce instances  
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Delete a set of instances
      gce:
        base_name: "{{ gce_ins_name }}"
        zone: europe-west1-b
        state: absent
        disk_size: 10



