- name: Add gce instances to LB 
  hosts: "{{ gce_ins_name }}"
  connection: local
  gather_facts: False

  tasks:

    - name: Output the ids_and_ports fact
      debug:
        msg: "{{ play_hosts }}"
      run_once: true
      delegate_to: localhost

    - name: Add to LB
      gce_lb:
        name: "{{ gce_lb_name }}"
        region: europe-west1
        members: "{{ play_hosts | join(',') }}"
      delegate_to: localhost
      run_once: true




