---
- name: gce actions
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "gce create"
    include_role: 
      name: gce
      tasks_from: gce_create

- name: gce add host
  hosts: localhost
  tasks:
  - include_role: 
      name: gce
      tasks_from: gce_add_host

- name: Deploy app
  import_playbook: app.yml

- name: gce add to LB
  hosts: localhost
  tasks:
  - include_role: 
      name: gce
      tasks_from: gce_lb