- name: install nginx
  hosts: all
  become: true

  roles:
    - user: ec2-user
    - role: nginxinc.nginx

  tasks:
    
  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /tmp/nginx.key.pem
    delegate_to: localhost

  - name: Generate an OpenSSL CSR
    openssl_csr:
      path: /tmp/nginx.csr
      privatekey_path: /tmp/nginx.key.pem
      common_name: "{{ ansible_nodename }}"
      subject_alt_name: '"{{ ansible_hostname }}"'
    delegate_to: localhost
  
  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /tmp/nginx.crt
      privatekey_path: /tmp/nginx.key.pem
      csr_path: /tmp/nginx.csr
      provider: selfsigned
    delegate_to: localhost

  - name: Creates Node cert directory
    file: 
      path: /etc/nginx/ssl
      state: directory
      owner: root
      group: root
      mode: 0600

  - name: Creates Node cert directory
    copy: 
      src=/tmp/nginx.crt 
      dest=/etc/nginx/ssl/nginx.crt 
      force=no
    notify: nginx



