- name: install nginx
  hosts: all
  user: ec2-user
  become: true

  roles:
    - role: nginxinc.nginx

  tasks:
  - name: create self-signed SSL cert
    shell: >
    openssl req -new -nodes -x509
    -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}"
    -days 3650 -keyout /etc/nginx/ssl/server.key
    -out /etc/nginx/ssl/server.crt
    -extensions v3_ca creates=/etc/nginx/ssl/server.crt
  notify: reload nginx