- name: install nginx
  hosts: "{{ ec2_nginx_scope }}"
  become: true
  user: ec2-user

  roles:
    - role: nginxinc.nginx

- name: Create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost

- name: Git clone the website
  git:
    repo: "{{ rep }}"
    version: "{{ ver }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost

- name: Copy conf to nodes 
  copy:
    src: "{{ r_tempfile.path }}/config/hello.conf" 
    dest: /etc/nginx/conf.d/default.conf 
  notify: restart_nginx

- name: Copy app to nodes 
  copy:
    src: "{{ r_tempfile.path }}/app/index.html" 
    dest: /usr/share/nginx/html/index.html 

handlers:
  - name: restart_nginx
    service:
      name: nginx
      state: restarted
    become: True

