- name: Stack actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes

  vars:
    state: "{{ state }}"


  tasks:

    - include_playbook: ec2.yml tags=deploy
    - include_playbook: app.yml tags=deploy    

