# - name: Stack actions
#   hosts: "*{{ ec2_scope }}"
#   gather_facts: yes
#   become: yes

#   vars:
#     state: "{{ state }}"


#   tasks:

- import_playbook: ec2.yml 
- import_playbook: app.yml

