- name: Stack actions
  hosts: "*{{ ec2_scope }}"
  gather_facts: yes
  become: yes

  vars:
    state: "{{ state }}"


  tasks:

    - name: Create ec2
      import_playbook: ec2.yml  
      tags: deploy

    - name: Deploy app
      import_playbook: app.yml  
      tags: deploy
