---

- name: Install needed packages
  yum:
    name: subscription-manager
    state: present

- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/


- name: Install needed packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  # - redhat-access-insights
    - pip

# - name: Insight Register
#   command: redhat-access-insights --register