---

- name: Install needed packages
  yum:
    name: subscription-manager
    state: present

- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"

- name: Add repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    
- name: Install needed packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  # - redhat-access-insights
    - python-pip
    - unzip
    - git-lfs

# - name: Insight Register
#   command: redhat-access-insights --register