---

# - name: Debug state value
#   debug:
#     msg: "{{ state }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2_scope }}"

- name: Node Register
  include_tasks: rhel_register.yml
  when: state == "present"

- name: Insight Register
  include_role:
    name: redhataccess.redhat-access-insights-client
  when: 
    - state == "present"
    - ansible_os_family == 'RedHat'

- name: NginX Install
  include_role:
    name: nginxinc.nginx
  when: state == "present"

- name: NginX Remove
  include_tasks: remove_nginx.yml
  when: state == "absent"