---

# - name: Debug state value
#   debug:
#     msg: "{{ state }}"

- name: Node Register
  include_tasks: rhel_register.yml
  when: state == "present"

- name: NginX Install
  include_role:
    name: nginxinc.nginx
  when: state == "present"

- name: NginX Remove
  include_tasks: remove_nginx.yml
  when: state == "absent"