- name: create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost
  run_once: yes
  become: no

- name: git clone the app specific version
  git:
    repo: "{{ app }}"
    version: "{{ version }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost
  run_once: yes
  become: no
  when:
    - version is defined and version != ""

- name: git clone the app latest comit
  git:
    repo: "{{ app }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost
  run_once: yes
  become: no
  when:
    - version is not defined or version == ""

- name: Remove git history  
  file:
    path: "{{ r_tempfile.path }}/.git"
    state: absent
  delegate_to: localhost
  run_once: yes
  become: no

- name: copy model from s3
  get_url:
    url: "{{ bucket }}/model-{{ version }}.model"
    dest: "{{ r_tempfile.path }}/app/model/model.model"
    force: yes
  delegate_to: localhost
  run_once: yes
  become: no

# - name: zip the app
#   archive:
#     path: "{{ r_tempfile.path }}/*"
#     dest: "{{ r_tempfile.path }}/app.zip"
#     format: zip
#   delegate_to: localhost
#   run_once: yes
#   become: no

# - name: copy zip to nodes 
#   copy:
#     src: "{{ r_tempfile.path }}/app.zip" 
#     dest: /app/
#   become: yes

- name: create app directory 
  file:
    path: /app
    state: directory
    mode: 0755

- name: copy app to nodes 
  copy:
    src: "{{ r_tempfile.path }}/" 
    dest: /app/
  become: yes

# - name: unzip app on target
#   unarchive:
#     src: "{{ r_tempfile.path }}/app.zip"
#     dest: /app
#   become: yes

- name: pip install requirements
  pip:
    requirements: /app/requirements.txt
    extra_args: --no-cache-dir
  become: yes

- name: customize gunicorn config
  blockinfile:
    path: /app/app/cfg.py
    marker: "# -- ANSIBLE MANAGED BLOCK -- #"
    content: |
      raw_env =  [
      'S3_BUCKET_NAME={{ results_bucket }}',
      'S3_KEY={{ AWS_KEY }}',
      'S3_SECRET={{ AWS_SECRET }}',
      ]

- name: start gunicorn
  environement:
    S3_KEY: "{{ AWS_ACCESS_KEY_ID }}"
    S3_SECRET: "{{ AWS_SECRET_ACCESS_KEY }}"
    S3_BUCKET_NAME: "{{ results_bucket }}"
  command: gunicorn -c cfg.py app:app
  args:
    chdir: /app/app
  async: 1
  poll: 0 
 
- name: Remove temp files
  file:
    path: "{{ r_tempfile.path }}"
    state: absent
  delegate_to: localhost
  run_once: yes
  become: no




