- name: Create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  connection: local
  run_once: yes
  become: no

- name: Git clone the app
  git:
    repo: "{{ app }}"
    version: "{{ ver }}"
    dest: "{{ r_tempfile.path }}"
  connection: local
  run_once: yes
  become: no

- name: Copy app to nodes 
  copy:
    src: "{{ r_tempfile.path }}/" 
    dest: /app/
  become: yes

