- name: Create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost

- name: Git clone the website
  git:
    repo: "{{ app }}"
    version: "{{ ver }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost

# - name: List git checkout
#   command: "ls {{ r_tempfile.path }}"
#   register: dir_out
#   delegate_to: localhost

# - name: Display checkout content
#   debug: var={{item}}
#   with_items: dir_out.stdout_lines
#   delegate_to: localhost

- name: Copy conf to nodes 
  copy:
    src: "{{ r_tempfile.path }}/config/hello.conf" 
    dest: /etc/nginx/conf.d/default.conf 
  # notify: restart_nginx

- name: Copy app to nodes 
  copy:
    src: "{{ r_tempfile.path }}/app/index.html" 
    dest: /usr/share/nginx/html/index.html 

