---
- name: Install RHSM and Insights
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - redhat-access-insights
    - subscription-manager
  
- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"

- name: Insight Register
  command: redhat-access-insights --register





