---

- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"

- name: Insight Register
  command: redhat-access-insights --register





