---
- name: Gather facts for instances name
  ec2_instance_facts:
    region: eu-west-1 
    filters: 
      "tag:Name": "{{ ec2_scope }}"
      "instance-state-name": running
  register: ec2

# - name: Output ec2
#   debug:
#     msg: "{{ ec2 }}"

- name: Build a list of ips and hostnames
  vars:
    ips_to_add: "{{ ec2.instances | map(attribute='private_ip_address') | list }}"
  set_fact:
    ips_to_add: "{{ ips_to_add }}"

- name: Add hosts
  add_host:
    name: "{{ item }}"
    groups: "tag_Name_{{ ec2_scope }}"
  with_items: "{{ ips_to_add }}" 

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ips_to_add }}"






