---
- name: Gather instance facts
  hosts: amazon
  gather_facts: yes
  user: ec2_user

- name: Change security group of an instance
  hosts: localhost
  gather_facts: no

  tasks: 

    - name: Variable values debug info
      debug:
        msg: "{{ ec2_region }}, {{ ec2_subnetid }}, {{ ec2_groupid }}"

    - name: ansible_play_hosts debug info
      debug:
        msg: "{{ ansible_play_hosts }}"

    - name: ansible_hostname debug info
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Hostvars debug info
      debug:
        msg: "{{ hostvars[ ansible_hostname ] }}"

    - name: Change security group of an instance
      ec2:
        state: running
        region: "{{ ec2_region }}" 
        vpc_subnet_id: "{{ ec2_subnetid }}"
        group_id: "{{ ec2_groupid }}"
        instance_ids:
          - "{{ ec2_instanceid }}"
      delegate_to: localhost


