---
- name: Provision a set of EC2 instances
  ec2:
     key_name: dcl
     state: present
     region: eu-west-1 
     instance_type: "{{ ec2_size }}"   
     image: "{{ ec2_ami }}"
     vpc_subnet_id: "{{ ec2_subnetid }}"
     assign_public_ip: no
     wait: true
     count: "{{ ec2_count }}"
     instance_tags:
        Name: "{{ ec2_scope }}"
     group_id: "{{ ec2_groupid }}"
  register: ec2
