---

- name: Provision a set of instances
  ec2:
     key_name: dcl
     state: present
     region: eu-west-1 
     instance_type: t2.micro
     image: ami-ecc27c95
     vpc_subnet_id: "{{ ec2_subnetid }}"
     assign_public_ip: no
     wait: true
     count: "{{ ec2_count }}"
     instance_tags:
        Name: "{{ ec2_scope }}"
     group_id: "{{ ec2_groupid }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"


