---
- name: Gather facts for instances name
  ec2_instance_facts:
    region: eu-west-1 
    filters: 
      "tag:Name": "{{ ec2_scope }}"
      "instance-state-name": running
  register: ec2

- name: Build a list of ids
  vars:
    ids_to_add: "{{ ec2.instances | map(attribute='instance_id') | list }}"
  set_fact:
    ids_to_add: "{{ ids_to_add }}"

- name: Build the list of instances id and ports
  vars:
    ids_and_ports: []
  set_fact:
    ids_and_ports: "{{ ids_and_ports +  [ {'Id': item, 'Port': 80} ] }}"
  with_items: "{{ ids_to_add }}"
  
# - name: Output the ids_and_ports fact
#   debug:
#     msg: "{{ ids_and_ports }}"

- name: Record existing LB target 
  elb_target_group_facts: 
    name: "{{ ec2_lb }}"
  register: elb

- debug: 
    msg: "{{ elb }}"

- name: Add Instances to LB target 
  elb_target_group:
    name: "{{ ec2_lb }}"
    protocol: https
    port: 80
    vpc_id: vpc-01234567
    region: eu-west-1 
    modify_targets: No
    state: present
    targets: "{{ ids_and_ports }}"




