
- name: Gather facts for instances name
  ec2_instance_facts:
    region: eu-west-1 
    filters: 
      "tag:Name": "{{ ec2_scope }}"
  register: ec2
  connection: localhost
  run_once: true

- name: Build a list of ids
  vars:
    ids_to_remove: "{{ ec2.instances | map(attribute='instance_id') | list }}"
  local_action:
    set_fact:
      ids_to_remove: "{{ ids_to_remove }}"
  run_once: true

- name: Remove a list of instances ids
  ec2:
     state: absent
     region: eu-west-1 
     wait: true
     instance_ids: "{{ ids_to_remove }}"
  when: ids_to_remove
  connection: localhost
  run_once: true

